# Github Actions workflow to run the following CI checks: 
# unit tests, linting, and documentation generation

#runs the workflow on any push to any branch
#also runs when any PR is opened or updated

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Auto-fix minor ESLint issues
        run: npm run lint -- --fix  
        continue-on-error: true

      - name: Run ESLint
        run: npm run lint || touch eslint.failed
        continue-on-error: true

      - name: Run Stylelint
        run: npm run stylelint || touch stylelint.failed
        continue-on-error: true

      - name: Run HTMLHint
        run: npm run htmlhint || touch htmlhint.failed
        continue-on-error: true

      - name: Log if any linter failed
        run: echo "Linters may have issues. Review the logs above"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Generate JSDoc
        run: npm run jsdoc

